"""Backup export and restore, version 3 — run with: python tests/test_restore.py

The export is the caller's *subtree*, keyed by unit slug rather than by the
old `platoon` string, and only an owner gets the `users` list. The restore is
owner-only, refuses anything that is not version 3 (a pre-A1 file has no unit
tree to land in), and replaces the caller's tree without touching anyone
else's.

Two A0 guarantees survive the rewrite and are still asserted here:

1. Explicit-id inserts (a restore preserves the file's ids) into a
   GENERATED BY DEFAULT AS IDENTITY column do not advance that column's
   sequence the way an ordinary insert does. Without resyncing the sequence
   before commit, the very next ordinary insert into that table collides with
   a restored id.
2. Restored rows carry the caller's root_id, so RLS keeps them — and only
   them — inside the caller's tenant.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))
sys.path.insert(0, _HERE)

import dbharness  # noqa: E402

_SCHEMA = dbharness.setup()

import server  # noqa: E402

TABLES = ('units', 'personnel', 'personnel_profile', 'scheduled_events',
          'duty_roster', 'report_history', 'settings')


def seed_data(tree):
    """One soldier (plus profile, absence, duty turn and report) per unit."""
    conn = dbharness.owner_conn()
    try:
        root = tree['root']
        ids = {}
        for unit, last in ((root, 'Root'), (tree['child'], 'Child')):
            pid = conn.execute(
                'INSERT INTO personnel (rank, last, first, status, unit_id, root_id) '
                "VALUES ('SGT', %s, 'One', 'present', %s, %s) RETURNING id",
                (last, unit, root)).fetchone()['id']
            ids[last] = pid
            conn.execute(
                'INSERT INTO personnel_profile (person_id, phone, root_id) VALUES (%s, %s, %s)',
                (pid, f'555-{last}', root))
            conn.execute(
                'INSERT INTO scheduled_events (person_id, status, from_date, to_date, state, unit_id, root_id) '
                "VALUES (%s, 'leave', '2026-01-01', '2026-01-05', 'scheduled', %s, %s)",
                (pid, unit, root))
            conn.execute(
                'INSERT INTO duty_roster (date, duty_type, person_id, last, unit_id, root_id) '
                "VALUES ('2026-01-02', 'CQ', %s, %s, %s, %s)", (pid, last, unit, root))
            conn.execute(
                'INSERT INTO report_history (unit_name, text, unit_id, root_id) '
                "VALUES (%s, 'all present', %s, %s)", (last, unit, root))
        conn.commit()
        return ids
    finally:
        conn.close()


def count_rows(root_id):
    conn = dbharness.owner_conn()
    try:
        return {t: conn.execute(f'SELECT COUNT(*) AS n FROM {t} WHERE root_id = %s',
                                (root_id,)).fetchone()['n'] for t in TABLES}
    finally:
        conn.close()


def audit_actions(root_id):
    conn = dbharness.owner_conn()
    try:
        return [r['action'] for r in conn.execute(
            'SELECT action FROM audit_log WHERE root_id = %s', (root_id,)).fetchall()]
    finally:
        conn.close()


def test_export_is_scoped_to_the_callers_subtree():
    t = dbharness.make_tree('Export Co')
    seed_data(t)
    c = server.app.test_client()

    dbharness.as_user(dbharness.make_user(t['child'], 'leader'))
    r = c.get('/api/backup')
    assert r.status_code == 200, r.get_data(as_text=True)
    data = r.get_json()
    assert data['version'] == 3, data['version']
    assert data['root_unit'] == t['child_slug'], data['root_unit']
    assert [u['slug'] for u in data['units']] == [t['child_slug']], data['units']
    assert [p['last'] for p in data['personnel']] == ['Child'], data['personnel']
    for row in data['personnel'] + data['scheduled_events'] + data['duty_roster'] + data['report_history']:
        assert 'unit_id' not in row and 'root_id' not in row, row
        assert row['unit'] == t['child_slug'], row
    assert [p['phone'] for p in data['personnel_profile']] == ['555-Child'], data['personnel_profile']
    assert all('root_id' not in p for p in data['personnel_profile']), data['personnel_profile']
    assert 'users' not in data, 'a leader never exports the user list'
    assert all(s['unit'] == t['child_slug'] for s in data['settings']), data['settings']

    dbharness.as_user(dbharness.make_user(t['root'], 'owner'))
    data = c.get('/api/backup').get_json()
    assert data['root_unit'] == 'export-co', data['root_unit']
    assert {u['slug'] for u in data['units']} == {'export-co', t['child_slug']}, data['units']
    assert {u['parent_slug'] for u in data['units']} == {None, 'export-co'}, data['units']
    assert {p['last'] for p in data['personnel']} == {'Root', 'Child'}, data['personnel']
    assert 'users' in data, 'an owner exports the user list'
    assert all('unit_id' not in u and u['unit'] for u in data['users']), data['users']
    assert any(s['unit'] is None and s['key'] == 'org_timezone' for s in data['settings']), data['settings']


def test_a_version_2_file_is_refused():
    t = dbharness.make_tree('Legacy Co')
    dbharness.as_user(dbharness.make_user(t['root'], 'owner'))
    c = server.app.test_client()
    r = c.post('/api/backup/restore', json={'version': 2, 'personnel': []})
    assert r.status_code == 400, (r.status_code, r.get_json())
    assert 'restore it before the A1 migration' in r.get_json()['error'], r.get_json()


def test_a_leader_cannot_restore():
    t = dbharness.make_tree('Leader Co')
    dbharness.as_user(dbharness.make_user(t['child'], 'leader'))
    c = server.app.test_client()
    r = c.post('/api/backup/restore', json={'version': 3, 'units': [], 'personnel': []})
    assert r.status_code == 403, (r.status_code, r.get_json())


def test_owner_round_trip_restores_its_own_export():
    t = dbharness.make_tree('Round Co')
    seed_data(t)
    other = dbharness.make_tree('Bystander Co')
    seed_data(other)
    other_before = count_rows(other['root'])

    owner = dbharness.make_user(t['root'], 'owner')
    dbharness.as_user(owner)
    c = server.app.test_client()
    exported = c.get('/api/backup').get_json()
    before = count_rows(t['root'])
    first = min(exported['personnel'], key=lambda p: p['id'])
    unit_creates_before = audit_actions(t['root']).count('UNIT_CREATE')

    # A unit named in the file that does not exist here is created under its parent.
    exported['units'].append({'slug': 'ghost-squad', 'parent_slug': t['child_slug'],
                              'kind': 'squad', 'name': 'Ghost Squad'})
    # The caller's own row must not be demoted by its own backup.
    exported['users'].append({'username': owner['username'], 'clerk_user_id': owner['clerk_user_id'],
                              'email': '', 'full_name': '', 'unit': t['child_slug'], 'role': 'leader'})

    r = c.post('/api/backup/restore', json=exported)
    assert r.status_code == 200, r.get_json()
    body = r.get_json()
    assert body['personnel'] == 2, body
    assert body['units_created'] == 1, body
    assert body['skipped_units'] == [], body
    assert body['skipped_users'] == [], body

    after = count_rows(t['root'])
    assert after == dict(before, units=before['units'] + 1), (before, after)
    assert count_rows(other['root']) == other_before, 'a second tree must be untouched'

    conn = dbharness.owner_conn()
    try:
        kept = conn.execute('SELECT last, unit_id, root_id FROM personnel WHERE id = %s',
                            (first['id'],)).fetchone()
        ghost = conn.execute('SELECT parent_id, root_id, kind FROM units WHERE slug = %s',
                             ('ghost-squad',)).fetchone()
        strays = conn.execute(
            'SELECT COUNT(*) AS n FROM personnel p LEFT JOIN units u ON u.id = p.unit_id '
            'WHERE p.root_id = %s AND (u.id IS NULL OR u.root_id != p.root_id)',
            (t['root'],)).fetchone()['n']
        me = conn.execute('SELECT role, unit_id FROM users WHERE username = %s',
                          (owner['username'],)).fetchone()
    finally:
        conn.close()
    assert kept and kept['last'] == first['last'], (first, kept)
    assert kept['root_id'] == t['root'] and kept['unit_id'] is not None, kept
    assert ghost['parent_id'] == t['child'] and ghost['root_id'] == t['root'] and ghost['kind'] == 'squad', ghost
    assert strays == 0, 'every restored row resolved to a unit in this tree'
    assert me == {'role': 'owner', 'unit_id': t['root']}, "a restore must not demote the caller's own row"

    actions = audit_actions(t['root'])
    assert 'BACKUP_RESTORE' in actions, actions
    assert actions.count('UNIT_CREATE') == unit_creates_before, (
        'restoring a unit that already existed must not log UNIT_CREATE')

    # The A0 sequence guarantee: an ordinary insert right after a restore must
    # not collide with a restored id. Explicit-id inserts never advance a
    # GENERATED BY DEFAULT AS IDENTITY sequence, so without the setval() resync
    # the next nextval() hands back an id this restore already used.
    r = c.post('/api/personnel', json={'rank': 'PVT', 'last': 'Fresh', 'first': 'New',
                                       'unit_id': t['child']})
    assert r.status_code == 201, (
        'a normal insert right after a restore must not collide with a restored id: '
        f'{r.status_code} {r.get_json()}')
    assert r.get_json()['id'] not in {p['id'] for p in exported['personnel']}, r.get_json()


def test_unknown_slugs_are_skipped_and_reported():
    t = dbharness.make_tree('Skip Co')
    dbharness.as_user(dbharness.make_user(t['root'], 'owner'))
    c = server.app.test_client()
    r = c.post('/api/backup/restore', json={
        'version': 3,
        'units': [],
        'personnel': [
            {'rank': 'SGT', 'last': 'Here', 'first': 'A', 'unit': t['child_slug']},
            {'rank': 'SGT', 'last': 'Nowhere', 'first': 'B', 'unit': 'no-such-unit'},
        ],
        'users': [
            {'username': 'newbie', 'clerk_user_id': 'clerk_newbie', 'email': 'n@example.com',
             'full_name': 'New Bie', 'unit': t['child_slug'], 'role': 'leader'},
            {'username': 'orphan', 'clerk_user_id': 'clerk_orphan', 'email': '',
             'full_name': '', 'unit': 'no-such-unit', 'role': 'leader'},
        ],
    })
    assert r.status_code == 200, r.get_json()
    body = r.get_json()
    assert body['personnel'] == 1, body
    assert body['skipped_units'] == ['no-such-unit'], body
    assert body['skipped_users'] == ['orphan'], body

    conn = dbharness.owner_conn()
    try:
        row = conn.execute('SELECT unit_id, role, root_id FROM users WHERE username = %s',
                           ('newbie',)).fetchone()
        gone = conn.execute("SELECT 1 FROM personnel WHERE last = 'Nowhere'").fetchone()
    finally:
        conn.close()
    assert row == {'unit_id': t['child'], 'role': 'leader', 'root_id': t['root']}, row
    assert gone is None, 'a row whose unit slug is unknown is not restored anywhere'


def test_a_username_owned_by_another_tree_is_skipped_not_fatal():
    """users.username is unique across every tenant, and RLS hides the row that
    owns it — so the upsert raises and would abort the whole restore. Each user
    goes in under its own savepoint instead: the clash is reported, the rest of
    the file lands, and the other tenant's row is untouched."""
    mine = dbharness.make_tree('Mine Co')
    theirs = dbharness.make_tree('Theirs Co')
    squatter = dbharness.make_user(theirs['child'], 'leader', username='shared-name')

    dbharness.as_user(dbharness.make_user(mine['root'], 'owner'))
    c = server.app.test_client()
    r = c.post('/api/backup/restore', json={
        'version': 3,
        'units': [],
        'personnel': [{'rank': 'SGT', 'last': 'Keep', 'first': 'Me', 'unit': mine['child_slug']}],
        'users': [{'username': 'shared-name', 'clerk_user_id': 'clerk_someone_else', 'email': '',
                   'full_name': '', 'unit': mine['child_slug'], 'role': 'owner'}],
    })
    assert r.status_code == 200, r.get_json()
    body = r.get_json()
    assert body['skipped_users'] == ['shared-name'], body
    assert body['personnel'] == 1, body

    conn = dbharness.owner_conn()
    try:
        rows = conn.execute('SELECT unit_id, role, root_id FROM users WHERE username = %s',
                            ('shared-name',)).fetchall()
        kept = conn.execute("SELECT root_id, unit_id FROM personnel WHERE last = 'Keep'").fetchone()
    finally:
        conn.close()
    assert len(rows) == 1, rows
    assert rows[0] == {'unit_id': squatter['unit_id'], 'role': 'leader',
                       'root_id': theirs['root']}, "the other tenant's row must be untouched"
    assert kept and kept['root_id'] == mine['root'] and kept['unit_id'] == mine['child'], (
        'the rest of the file must still land after a skipped user')


def main():
    try:
        test_export_is_scoped_to_the_callers_subtree()
        test_a_version_2_file_is_refused()
        test_a_leader_cannot_restore()
        test_owner_round_trip_restores_its_own_export()
        test_unknown_slugs_are_skipped_and_reported()
        test_a_username_owned_by_another_tree_is_skipped_not_fatal()
        print('ok')
    finally:
        dbharness.teardown(_SCHEMA)


if __name__ == '__main__':
    main()
