"""scripts/platoons-to-units.py against a production-shaped A0 database.

Run with: python tests/test_units_migration.py

Builds the A0 schema by hand (the CREATE TABLEs as they were before this
branch), fills it the way production looks — three platoons, soldiers on ids
1 and 3, two admins, three 2nd-only leaders, one multi-platoon leader, an
empty-access user, six tdy_* settings and the unit names — then runs the
cutover order for real: `import server` (init_db adds the new columns), then
the script as the owner, then the app as the owner user.
"""
import json
import os
import subprocess
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_HERE))
sys.path.insert(0, _HERE)

import psycopg  # noqa: E402
from psycopg.rows import dict_row  # noqa: E402

import dbharness  # noqa: E402

_SCHEMA = dbharness.setup()

A0_DDL = """
CREATE TABLE personnel (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, rank TEXT, last TEXT, first TEXT,
  status TEXT DEFAULT 'present', notes TEXT DEFAULT '', from_date TEXT DEFAULT '', to_date TEXT DEFAULT '',
  present_date TEXT DEFAULT '', platoon TEXT DEFAULT '2nd');
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL, is_admin INTEGER DEFAULT 0, platoons TEXT DEFAULT '', clerk_user_id TEXT DEFAULT '',
  email TEXT DEFAULT '', full_name TEXT DEFAULT '', pin_hash TEXT DEFAULT '');
CREATE TABLE audit_log (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, timestamp TEXT DEFAULT '',
  user_id INTEGER DEFAULT 0, username TEXT DEFAULT '', action TEXT DEFAULT '', details TEXT DEFAULT '', platoon TEXT DEFAULT '');
CREATE TABLE duty_roster (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date TEXT NOT NULL, platoon TEXT NOT NULL,
  duty_type TEXT NOT NULL DEFAULT 'CQ', person_id INTEGER, rank TEXT DEFAULT '', last TEXT DEFAULT '', first TEXT DEFAULT '', notes TEXT DEFAULT '');
CREATE TABLE scheduled_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, person_id INTEGER NOT NULL,
  platoon TEXT NOT NULL, status TEXT NOT NULL, from_date TEXT DEFAULT '', to_date TEXT DEFAULT '', notes TEXT DEFAULT '',
  created_at TEXT DEFAULT '', state TEXT DEFAULT 'scheduled', location TEXT DEFAULT '',
  FOREIGN KEY(person_id) REFERENCES personnel(id) ON DELETE CASCADE);
CREATE TABLE personnel_profile (person_id INTEGER PRIMARY KEY, phone TEXT DEFAULT '', email TEXT DEFAULT '',
  FOREIGN KEY(person_id) REFERENCES personnel(id) ON DELETE CASCADE);
CREATE TABLE invites (token TEXT PRIMARY KEY, label TEXT DEFAULT '', platoons TEXT DEFAULT '', is_admin INTEGER DEFAULT 0,
  created_by TEXT DEFAULT '', created_at TEXT DEFAULT '', expires_at TEXT DEFAULT '', accepted_at TEXT DEFAULT '', accepted_by TEXT DEFAULT '');
CREATE TABLE report_history (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, platoon TEXT NOT NULL,
  unit_name TEXT DEFAULT '', text TEXT NOT NULL, created_at TEXT DEFAULT '', created_by TEXT DEFAULT '');
"""


def build_a0_fixture():
    conn = dbharness.owner_conn()
    conn.execute(A0_DDL)
    people = [(1, 'CW2', 'Carr', 'Jonathon', 'present', 'hq'), (2, 'SGT', 'Two', 'A', 'tdy', '1st'),
              (3, 'CW2', 'Bennett', 'Christopher', 'leave', '2nd'), (7, 'SPC', 'Seven', 'B', 'present', '2nd')]
    for row in people:
        conn.execute('INSERT INTO personnel (id, rank, last, first, status, platoon) VALUES (%s, %s, %s, %s, %s, %s)', row)
    conn.execute("INSERT INTO personnel_profile (person_id, phone) VALUES (1, '555')")
    conn.execute("INSERT INTO scheduled_events (id, person_id, platoon, status, from_date, to_date, state) VALUES "
                 "(10, 2, '1st', 'tdy', '2026-09-01', '', 'active'), (11, 3, '2nd', 'leave', '2026-09-10', '2026-10-10', 'active'), "
                 "(12, 3, '2nd', 'pass', '2026-08-01', '2026-08-02', 'completed')")
    conn.execute("INSERT INTO duty_roster (date, platoon, person_id, rank, last, first) VALUES ('2026-09-20', '2nd', 7, 'SPC', 'Seven', 'B')")
    conn.execute("INSERT INTO report_history (platoon, unit_name, text) VALUES ('2nd', '2nd Platoon', 'r1'), ('1st', '1st', 'r2')")
    conn.execute("INSERT INTO audit_log (username, action, platoon) VALUES ('boss', 'LOGIN', ''), ('boss', 'ADD_PERSON', '2nd'), ('system', 'ABSENCE_ACTIVATE', '1st')")
    users = [('jon', 1, '*', 'c1'), ('jca', 1, '*', 'c2'), ('cal', 0, '2nd', 'c3'), ('ben', 0, '2nd', 'c4'),
             ('multi', 0, '1st,2nd', 'c5'), ('nobody', 0, '', 'c6'), ('local.only', 0, '2nd', '')]
    for u in users:
        conn.execute("INSERT INTO users (username, password_hash, is_admin, platoons, clerk_user_id, email) VALUES (%s, 'x', %s, %s, %s, %s)",
                     (u[0], u[1], u[2], u[3], f'{u[0]}@example.com'))
    conn.execute("INSERT INTO invites (token, label, platoons, is_admin, expires_at) VALUES ('t-pending', 'p', '2nd', 0, '2099-01-01 00:00:00'), "
                 "('t-admin', 'a', '*', 1, '2099-01-01 00:00:00')")
    for key, value in [('org_timezone', 'America/Chicago'), ('unit_name', 'x'), ('unit_name_1st', '1st Platoon'),
                       ('unit_name_2nd', '2nd Platoon Accountability'), ('unit_name_hq', 'HQ Platoon'),
                       ('tdy_schools_1st', '["CCNA"]'), ('tdy_schools_2nd', '["AWOIC","C3"]'), ('tdy_schools_hq', '[]'),
                       ('tdy_locations_1st', '[]'), ('tdy_locations_2nd', '["Bliss"]'), ('tdy_locations_hq', '[]')]:
        conn.execute('INSERT INTO settings (key, value) VALUES (%s, %s)', (key, value))
    conn.commit(); conn.close()


def run_script(*args):
    proc = subprocess.run([sys.executable, os.path.join(os.path.dirname(_HERE), 'scripts', 'platoons-to-units.py'), *args],
                          capture_output=True, text=True, env=os.environ)
    return proc


def main():
    # A failed assertion between owner_conn() and its close() would otherwise
    # leave that connection holding the schema, and teardown's DROP SCHEMA
    # would block on it forever instead of the test failing.
    conn = None
    try:
        build_a0_fixture()
        import server  # noqa: F401  — init_db() runs here: additive columns, RLS, functions

        # An invite that maps nowhere would fail `invites.unit_id NOT NULL` with
        # a column name; the script names the token instead and rolls back whole.
        tables = ['personnel', 'scheduled_events', 'duty_roster', 'report_history', 'audit_log',
                  'personnel_profile', 'settings', 'users', 'invites', 'units']

        def counts():
            conn = dbharness.owner_conn()
            try:
                return {t: conn.execute(f'SELECT count(*) AS n FROM {t}').fetchone()['n'] for t in tables}
            finally:
                conn.close()
        conn = dbharness.owner_conn()
        conn.execute("INSERT INTO invites (token, label, platoons, is_admin, expires_at) "
                     "VALUES ('t-orphan', 'o', '', 0, '2099-01-01 00:00:00')")
        conn.commit(); conn.close()
        pre = counts()
        orphaned = run_script('Headquarters Company')
        out = orphaned.stdout + orphaned.stderr
        assert orphaned.returncode == 1, out
        assert 't-orphan' in out, out
        assert counts() == pre, (pre, counts())
        assert pre['units'] == 0, pre
        conn = dbharness.owner_conn()
        conn.execute("DELETE FROM invites WHERE token = 't-orphan'")
        conn.commit(); conn.close()

        proc = run_script('Headquarters Company')
        assert proc.returncode == 0, proc.stdout + proc.stderr
        assert 'migration verified' in proc.stdout, proc.stdout

        conn = dbharness.owner_conn()
        units = conn.execute('SELECT * FROM units ORDER BY id').fetchall()
        assert [u['slug'] for u in units] == ['headquarters-company', '1stplatoon', '2ndplatoon', 'hq'], units
        root = units[0]
        assert root['parent_id'] is None and root['root_id'] == root['id'] and root['kind'] == 'company'
        by_slug = {u['slug']: u for u in units}
        assert by_slug['2ndplatoon']['name'] == '2nd Platoon Accountability' and by_slug['2ndplatoon']['parent_id'] == root['id']
        assert all(u['root_id'] == root['id'] for u in units)

        p = {r['id']: r for r in conn.execute('SELECT * FROM personnel ORDER BY id').fetchall()}
        assert (p[1]['last'], p[1]['unit_id']) == ('Carr', by_slug['hq']['id'])
        assert (p[3]['last'], p[3]['unit_id']) == ('Bennett', by_slug['2ndplatoon']['id'])
        assert 'platoon' not in p[1], 'platoon column must be gone'
        for t in ('personnel', 'scheduled_events', 'duty_roster', 'report_history', 'audit_log', 'personnel_profile', 'settings'):
            n = conn.execute(f'SELECT count(*) AS n FROM {t} WHERE root_id IS DISTINCT FROM %s', (root['id'],)).fetchone()['n']
            assert n == 0, f'{t}: {n} rows outside the root'
        ev = {r['id']: r for r in conn.execute('SELECT * FROM scheduled_events').fetchall()}
        assert ev[10]['unit_id'] == by_slug['1stplatoon']['id'] and ev[10]['to_date'] == ''
        audit = conn.execute("SELECT action, unit_id FROM audit_log ORDER BY id").fetchall()
        assert audit[0]['unit_id'] is None and audit[1]['unit_id'] == by_slug['2ndplatoon']['id']

        u = {r['username']: r for r in conn.execute('SELECT * FROM users').fetchall()}
        assert (u['jon']['unit_id'], u['jon']['role']) == (root['id'], 'owner')
        assert (u['jca']['unit_id'], u['jca']['role']) == (root['id'], 'owner')
        assert (u['cal']['unit_id'], u['cal']['role']) == (by_slug['2ndplatoon']['id'], 'leader')
        assert (u['multi']['unit_id'], u['multi']['role']) == (root['id'], 'leader')
        assert u['nobody']['unit_id'] is None and u['nobody']['root_id'] is None
        assert 'is_admin' not in u['jon'] and 'platoons' not in u['jon']
        inv = {r['token']: r for r in conn.execute('SELECT * FROM invites').fetchall()}
        assert (inv['t-pending']['unit_id'], inv['t-pending']['role']) == (by_slug['2ndplatoon']['id'], 'leader')
        assert (inv['t-admin']['unit_id'], inv['t-admin']['role']) == (root['id'], 'owner')

        s = {(r['unit_id'], r['key']): r['value'] for r in conn.execute('SELECT unit_id, key, value FROM settings').fetchall()}
        assert s[(None, 'org_timezone')] == 'America/Chicago'
        assert s[(by_slug['2ndplatoon']['id'], 'tdy_schools')] == '["AWOIC","C3"]'
        assert not [k for k in s if k[1].startswith('unit_name')], 'unit_name settings must be gone'
        seqs = conn.execute("SELECT last_value, is_called FROM personnel_id_seq").fetchone()
        assert (seqs['last_value'], seqs['is_called']) == (7, True)
        conn.close()

        # Refuses to run twice.
        again = run_script('Headquarters Company')
        assert again.returncode != 0 and 'already' in (again.stdout + again.stderr)

        # And the app sees the tree as the owner.
        dbharness.as_user(dict(u['jon']))
        c = server.app.test_client()
        assert len(c.get('/api/units').get_json()) == 4
        roster = c.get(f"/api/personnel?unit={by_slug['2ndplatoon']['id']}").get_json()
        assert {r['last'] for r in roster} == {'Bennett', 'Seven'}, roster
        company = c.get(f"/api/personnel?unit={root['id']}").get_json()
        assert len(company) == 4, 'the root view is the whole company'
        print('ok')
    finally:
        if conn is not None:
            conn.close()
        dbharness.teardown(_SCHEMA)


if __name__ == '__main__':
    main()
