"""Backup/restore — run with: python tests/test_restore.py

Covers the bugs the Postgres port introduced into import_backup(), none of
which any other test exercised:

1. Explicit-id inserts (admin restores preserve the backup's ids) into a
   GENERATED BY DEFAULT AS IDENTITY column do not advance that column's
   sequence the way an ordinary insert does. Without resyncing the sequence
   before commit, the very next ordinary insert into that table can collide
   with a restored id and fail.
2. A row with no id in the backup used to pass Python None straight through
   as the id column's value. SQLite's ROWID auto-assigns on an explicit NULL;
   Postgres's identity columns are NOT NULL and only auto-assign when the
   column is omitted, so an explicit NULL is a constraint violation instead.
3. A restore mixing explicit-id and id-less rows in one batch can collide
   *within itself*: an id-less row auto-assigns from wherever the sequence
   already sits, which is exactly the id a not-yet-processed explicit-id row
   later in the same batch might use, if both are handled in one interleaved
   pass. import_backup() now inserts every explicit-id row first, resyncs,
   then lets id-less rows auto-assign — clear of everything this batch used.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import dbharness  # noqa: E402
_schema = dbharness.setup()

import server  # noqa: E402  (must follow dbharness.setup())

ADMIN = {'is_admin': 1, 'id': 1, 'username': 'boss', 'platoons': '*'}
SECOND_ONLY = {'is_admin': 0, 'id': 2, 'username': 'sarge', 'platoons': '2nd'}


def as_user(user):
    server.get_current_user = lambda: user


def personnel_seq_next_value():
    """The id an ordinary /api/personnel insert would get right now, without
    consuming it (unlike calling nextval() directly)."""
    conn = server.get_db()
    seq = conn.execute("SELECT pg_get_serial_sequence('personnel', 'id') AS n").fetchone()['n']
    last_value = conn.execute(f'SELECT last_value FROM {seq}').fetchone()['last_value']
    conn.close()
    return last_value + 1


def main():
    c = server.app.test_client()

    # 1. Admin restore with explicit ids: the rows land with those ids.
    # Pick ids starting exactly at the personnel sequence's next value, so
    # that restoring them is the scenario where an unsynced sequence would
    # actually collide with the next ordinary insert (see step 2).
    first_id = personnel_seq_next_value()
    second_id = first_id + 1
    as_user(ADMIN)
    r = c.post('/api/backup/restore', json={
        'version': 2,
        'personnel': [
            {'id': first_id, 'rank': 'SGT', 'last': 'Alpha', 'first': 'One',
             'status': 'present', 'platoon': '2nd'},
            {'id': second_id, 'rank': 'SPC', 'last': 'Bravo', 'first': 'Two',
             'status': 'present', 'platoon': '2nd'},
        ],
    })
    assert r.status_code == 200, r.get_json()
    assert r.get_json()['personnel'] == 2, r.get_json()

    conn = server.get_db()
    rows = {row['id']: row for row in conn.execute('SELECT * FROM personnel').fetchall()}
    conn.close()
    assert set(rows) == {first_id, second_id}, rows
    assert rows[first_id]['last'] == 'Alpha' and rows[second_id]['last'] == 'Bravo', rows

    # 2. Regression test for the sequence bug (Finding 1): an ordinary insert
    #    right after an admin restore must not collide with a restored id.
    #    Without the setval() resync, Postgres's identity sequence is still
    #    sitting where it was before the restore (explicit-id inserts never
    #    advance it), so the very next nextval() reproduces `first_id` exactly
    #    — the id this restore just used — and the insert below 500s.
    r = c.post('/api/personnel', json={'rank': 'PVT', 'last': 'Charlie', 'first': 'Three', 'platoon': '2nd'})
    assert r.status_code == 201, (
        'a normal insert right after an admin restore must not collide with a '
        f'restored id: {r.status_code} {r.get_json()}'
    )
    new_id = r.get_json()['id']
    assert new_id not in (first_id, second_id), f'new person reused a restored id: {new_id}'

    # 3. Non-admin restore: succeeds and assigns fresh ids rather than 500ing.
    #    Regression test for Finding 2 — the non-admin path never trusts a
    #    backup id for personnel or scheduled_events, and used to pass that
    #    "no id" straight through as an explicit NULL.
    as_user(SECOND_ONLY)
    r = c.post('/api/backup/restore', json={
        'version': 2,
        'personnel': [
            # The backup's own id (555) is never trusted for a non-admin
            # restore; it only exists here so scheduled_events below can
            # reference this row via person_id_map.
            {'id': 555, 'rank': 'SGT', 'last': 'Delta', 'first': 'Four',
             'status': 'present', 'platoon': '2nd'},
        ],
        'scheduled_events': [
            {'person_id': 555, 'platoon': '2nd', 'status': 'leave',
             'from_date': '2026-01-01', 'to_date': '2026-01-05'},
        ],
    })
    assert r.status_code == 200, r.get_json()
    assert r.get_json()['personnel'] == 1, r.get_json()

    conn = server.get_db()
    person = conn.execute("SELECT * FROM personnel WHERE last = 'Delta'").fetchone()
    conn.close()
    assert person is not None, 'non-admin restore should have inserted the person'
    assert person['id'] != 555, 'non-admin restore must assign a fresh id, not trust the backup id'

    conn = server.get_db()
    event = conn.execute('SELECT * FROM scheduled_events WHERE person_id = %s', (person['id'],)).fetchone()
    conn.close()
    assert event is not None, 'the scheduled_event should have been reattached to the remapped person'
    assert event['status'] == 'leave', event

    # 4. Regression test for the mixed-batch collision (Finding 2 follow-up):
    #    an id-less row listed *before* an explicit-id row in the same admin
    #    restore payload must not collide with it. This is exactly the order
    #    a single interleaved pass got wrong — the id-less row auto-assigned
    #    from the stale pre-restore sequence position before the explicit row
    #    later in the same batch claimed that same id outright.
    as_user(ADMIN)
    clash_id = personnel_seq_next_value()
    r = c.post('/api/backup/restore', json={
        'version': 2,
        'personnel': [
            {'rank': 'PFC', 'last': 'Echo', 'first': 'Five', 'status': 'present', 'platoon': '2nd'},
            {'id': clash_id, 'rank': 'CPL', 'last': 'Foxtrot', 'first': 'Six',
             'status': 'present', 'platoon': '2nd'},
        ],
    })
    assert r.status_code == 200, r.get_json()
    assert r.get_json()['personnel'] == 2, r.get_json()

    conn = server.get_db()
    rows = conn.execute('SELECT * FROM personnel').fetchall()
    conn.close()
    ids = [row['id'] for row in rows]
    assert len(ids) == len(set(ids)), f'mixed restore batch produced duplicate ids: {ids}'
    by_last = {row['last']: row for row in rows}
    assert by_last['Foxtrot']['id'] == clash_id, by_last['Foxtrot']
    assert by_last['Echo']['id'] != clash_id, (
        'the id-less row (listed first) must not have collided with the '
        'explicit-id row (listed second) in the same batch'
    )

    print('ok')
    dbharness.teardown(_schema)


if __name__ == '__main__':
    main()
